### ISSUE TITLE
max() arg error from update_db.sh

### ISSUE THREAD

**Issue by ktran9891** [ulissigroup/GASpy#33]
```
 ERROR    [[/project/projectdirs/m2755/GASpy_conda/lib/python2.7/site-packages/luigi-2.6.1-py2.7.egg/luigi/worker.py::210][run]]: [pid 628] Worker Worker(salt=449703850, workers=1, host=cori11, username=ktran, pid=132328) failed    FingerprintRelaxedAdslab(parameters={"bulk": {"max_atoms": 50, "relaxed": true, "vasp_settings": {"kpts": [10, 10, 10], "isym": 0, "pp": "PBE", "prec": "Accurate", "pp_version": "5.4", "isif": 7, "ibrion": 1, "gga": "RP", "encut": 500.0, "ediff": 1e-08, "nsw": 100}, "mpid": "mp-1490"}, "slab": {"get_slab_settings": {"max_broken_bonds": 0, "bonds": null, "tol": 0.3, "symmetrize": false}, "shift": 0.07, "relaxed": true, "slab_generate_settings": {"primitive": true, "min_vacuum_size": 20.0, "lll_reduce": false, "max_normal_search": 1, "min_slab_size": 7.0, "center_slab": true}, "miller": [1, 1, 0], "vasp_settings": {"pp": "PBE", "isym": 0, "kpts": [4, 4, 1], "encut": 350, "pp_version": "5.4", "isif": 0, "ibrion": 2, "gga": "RP", "ediffg": -0.03, "nsw": 100, "lreal": "Auto"}, "max_miller": 2, "top": true}, "gas": {"relaxed": true, "vasp_settings": {"kpts": [1, 1, 1], "pp": "PBE", "encut": 350, "pp_version": "5.4", "isif": 0, "ibrion": 2, "gga": "RP", "ediffg": -0.03, "nsw": 100}, "gasname": "CO"}, "adsorption": {"numtosubmit": 2, "adsorbates": [{"name": "OH", "adsorption_site": "[  2.7    1.76  20.16]", "atoms": "63636f70795f7265670a5f7265636f6e7374727563746f720a70310a28636173652e61746f6d730a41746f6d730a70320a635f5f6275696c74696e5f5f0a6f626a6563740a70330a4e745270340a286470350a5327696e666f270a70360a286470370a7353275f63656c6c64697370270a70380a636e756d70792e636f72652e6d756c746961727261790a5f7265636f6e7374727563740a70390a28636e756d70790a6e6461727261790a7031300a2849300a74532762270a74527031310a2849310a2849330a49310a74636e756d70790a64747970650a7031320a2853276638270a49300a49310a74527031330a2849330a53273c270a4e4e4e492d310a492d310a49300a74624930300a53275c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c783030270a74627353275f63616c63270a7031340a4e735327617272617973270a7031350a28647031360a5327706f736974696f6e73270a7031370a67390a286731300a2849300a74532762270a74527031380a2849310a2849320a49330a746731330a4930300a53275c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7862385c7831655c7838355c786562515c7862385c7865653f270a74627353276e756d62657273270a7031390a67390a286731300a2849300a74532762270a74527032300a2849310a2849320a746731320a2853276938270a49300a49310a74527032310a2849330a53273c270a4e4e4e492d310a492d310a49300a74624930300a53275c7830385c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830315c7830305c7830305c7830305c7830305c7830305c7830305c783030270a7462737353275f706263270a7032320a67390a286731300a2849300a74532762270a74527032330a2849310a2849330a746731320a2853276231270a49300a49310a74527032340a2849330a53277c270a4e4e4e492d310a492d310a49300a74624930300a53275c7830305c7830305c783030270a74627353275f63656c6c270a7032350a67390a286731300a2849300a74532762270a74527032360a2849310a2849330a49330a746731330a4930300a53275c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c7830305c783030270a74627353275f636f6e73747261696e7473270a7032370a286c7032380a73622e"}], "relaxed": true, "slabrepeat": "(1, 1)", "num_slab_atoms": 0, "vasp_settings": {"pp": "PBE", "isym": 0, "kpts": [4, 4, 1], "encut": 350, "pp_version": "5.4", "isif": 0, "ibrion": 2, "gga": "RP", "ediffg": -0.03, "nsw": 200, "lreal": "Auto"}, "min_xy": 4.5}})
 Traceback (most recent call last):
   File "/project/projectdirs/m2755/GASpy_conda/lib/python2.7/site-packages/luigi-2.6.1-py2.7.egg/luigi/worker.py", line 191, in run
     new_deps = self._run_get_new_deps()
   File "/project/projectdirs/m2755/GASpy_conda/lib/python2.7/site-packages/luigi-2.6.1-py2.7.egg/luigi/worker.py", line 129, in _run_get_new_deps
     task_gen = self.task.run()
   File "/global/project/projectdirs/m2755/GASpy/tasks.py", line 996, in run
     fp_final = utils.fingerprint_atoms(calc_e_dict['atoms'])
   File "/global/project/projectdirs/m2755/GASpy/gaspy/utils.py", line 338, in fingerprint_atoms
     coordinated_atoms = vcf.get_coordinated_sites(len(atoms)-1, 0.8)
   File "/project/projectdirs/m2755/GASpy_conda/lib/python2.7/site-packages/pymatgen-2017.7.4-py2.7-linux-x86_64.egg/pymatgen/analysis/structure_analyzer.py", line 140, in get_coordinated_sites
     for site, weight in self.get_voronoi_polyhedra(n).items():
   File "/project/projectdirs/m2755/GASpy_conda/lib/python2.7/site-packages/pymatgen-2017.7.4-py2.7-linux-x86_64.egg/pymatgen/analysis/structure_analyzer.py", line 101, in get_voronoi_polyhedra
     maxangle = max(results.values())
 ValueError: max() arg is an empty sequence
```

**Comment by ktran9891** [comment]
Probably not an issue after we upgraded pymatgen.
